app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

/*
 * Routes needed for a single conference.
 */
use App\Scopes\TenantScope;

function conference_routes() {

	Route::group( [ 'middleware' => 'locale' ], function () {

		Route::get( '/', 'PublicController@index' );
		Route::get( 'manifest.json', 'ManifestController@get' );
		Route::auth();
		Route::get( 'twofactor', 'Auth\AuthController@showTwoFactorForm' );
		Route::post( 'twofactor', 'Auth\AuthController@twoFactor' );

		Route::group( [ 'prefix' => 'invite/{token}' ], function () {
			Route::get( '/', 'InviteController@invite' );

			Route::post( 'accept', [ 'uses' => 'InviteController@accept', 'middleware' => 'auth' ] );
			Route::post( 'refuse', 'InviteController@refuse' );
		} );

		Route::get( 'language/{locale}', 'LocaleController@change' );

		Route::group( [ 'prefix' => 'me', 'middleware' => 'auth' ], function () {
			Route::get( 'profile', 'AccountController@getProfile' );
			Route::post( 'profile', 'AccountController@postProfile' );
			Route::get( 'security', 'AccountController@getSecurity' );
			Route::post( 'security', 'AccountController@postSecurity' );
			Route::post( 'twofactor', 'AccountController@postTwoFactor' );
			Route::delete( 'twofactor', 'AccountController@deleteTwoFactor' );
		} );

		Route::group( [ 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'committee' ], function () {

			Route::get( '/', 'DashboardController@view' );

			// Session Types
			Route::resource( 'session-type', 'SessionTypeController', [
				'only' => [
					'index',
					'store',
					'update',
					'destroy'
				]
			] );

			// Email
			Route::group( [ 'prefix' => 'email' ], function () {

				Route::get( '/', 'EmailController@index' );
				Route::get( 'compose', 'EmailController@compose' );
				Route::post( 'send', 'EmailController@send' );

			} );

			//Organizing committee
			\App\Http\Controllers\Admin\OrganizingCommitteeController::routes();

			// Settings
			Route::get( 'settings/conference', 'SettingsController@show' );
			Route::post( 'settings/conference', 'SettingsController@store' );

		} );

	} );

}

/*
 * Routes needed for network admin.
 */
function admin_routes() {
	Route::group( [ 'namespace' => 'Network', 'middleware' => 'locale' ], function () {
		// Authentication Routes...
		Route::get( 'login', 'Auth\AuthController@showLoginForm' );
		Route::post( 'login', 'Auth\AuthController@login' );
		Route::get( 'twofactor', 'Auth\AuthController@showTwoFactorForm' );
		Route::post( 'twofactor', 'Auth\AuthController@twoFactor' );
		Route::get( 'logout', 'Auth\AuthController@logout' );

		// Password Reset Routes...
		Route::get( 'password/reset/{token?}', 'Auth\PasswordController@showResetForm' );
		Route::post( 'password/email', 'Auth\PasswordController@sendResetLinkEmail' );
		Route::post( 'password/reset', 'Auth\PasswordController@reset' );

		Route::group( [ 'prefix' => 'admin', 'middleware' => 'auth' ], function () {
			Route::get( '/', 'DashboardController@view' );
			Route::resource( 'conference', 'ConferenceController' );
			Route::resource( 'user', 'UserController', [ 'except' => [ 'show' ] ] );
			Route::group( [ 'prefix' => 'account' ], function () {
				Route::get( 'profile', 'AccountController@getProfile' );
				Route::post( 'profile', 'AccountController@postProfile' );
				Route::get( 'security', 'AccountController@getSecurity' );
				Route::post( 'security', 'AccountController@postSecurity' );
				Route::post( 'twofactor', 'AccountController@postTwoFactor' );
				Route::delete( 'twofactor', 'AccountController@deleteTwoFactor' );
			} );
		} );
	} );
}

Route::group( [ 'middleware' => 'web' ], function () {

	Route::group( [ 'prefix' => 'install' ], function () {
		Route::get( '/', 'InstallerController@index' );
		Route::get( 'form', 'InstallerController@form' );
		Route::post( 'form', 'InstallerController@store' );
		Route::get( 'success', 'InstallerController@success' );
	} );

	Route::group( [ 'prefix' => 'media' ], function () {
		Route::post( 'upload', 'FileController@upload' );
		Route::get( '{name}', 'FileController@get' )->where( 'name', '(.*)' );
	} );

	if ( Config::get( 'econf.multi' ) ) {
		// Multi
		Route::get( '/', function () {
			return view( 'welcome' );
		} );

		Route::get( 'manifest.json', 'Network\ManifestController@get' );

		admin_routes();

		Route::group( [ 'prefix' => '{conf_slug}', 'middleware' => 'multi' ], function () {
			conference_routes();
		} );

	} else {
		// Single
		Setting::setExtraColumns( array(
			TenantScope::$tenant_col => null
		) );
		conference_routes();
	}


} );

app/User.php
<?php

namespace App;

use App\Traits\HasDataFieldTrait;
use App\Traits\TenantableTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Gravatar;
use Illuminate\Support\Arr;

class User extends Authenticatable {

	use TenantableTrait;
	use HasDataFieldTrait;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'email',
		'password',
	];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];

	protected $casts = [
		'data' => 'array',
	];

	public function getPhotoAttribute() {
		return Gravatar::src( $this->email );
	}

	public function getShortNameAttribute() {
		$split = explode( ' ', $this->name );
		if ( count( $split ) < 2 ) {
			return $this->name;
		}
		return $split[0] . ' ' . $split[count( $split ) - 1];
	}

	public function committees() {
		return $this->belongsToMany( 'App\Committee' )->withPivot( 'chair' )->withTimestamps();
	}

}

resources/views/admin/committee.blade.php
@extends('layouts.admin')

@section('content')
    <header class="content-header">
        <h1>{{ $committee->full_name() }}</h1>

        {!! Breadcrumbs::render('committee', $committee) !!}
    </header>

    <section class="content">

        @include('flash::message')

        <p>
            <a class="btn btn-default" data-toggle="modal" data-target="#addUserModal">
                <span class="fa fa-user-plus"></span>
                {{ trans('econf.committee.invite_user') }}
            </a>
        </p>

        <div class="box box-default">
            <div class="box-body no-padding">

                <table class="table">
                    <thead>
                    <tr>
                        <th style="width: 1.8em;"></th>
                        <th>{{ trans('econf.user.name') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>
                                <img src="{{ $user->photo }}" alt="{{ $user->short_name }}" class="img-circle"
                                     style="height: 1.8em; width: auto; margin: -.4em 0;">
                            </td>
                            <td>
                                {{ $user->name }}
                                @if($user->pivot->chair)
                                    <span class="label label-default">{{ trans('econf.committee.chair') }}</span>
                                @endif
                            </td>
                            <td class="text-right">
                                @if($user->id != Auth::id())
                                    @if($user->pivot->chair)
                                        {!! BootForm::open()->action(m_action('\\'.$class.'@removeChair', $user->id))->delete() !!}
                                    @else
                                        {!! BootForm::open()->action(m_action('\\'.$class.'@makeChair', $user->id))->put() !!}
                                    @endif
                                    <div class="btn-group btn-group-xs">
                                        @if($user->pivot->chair)
                                            <button class="btn btn-default btn-xs" type="submit"
                                                    title="{{ trans('econf.committee.remove_chair') }}">
                                                <span class="fa fa-star-o"></span>
                                            </button>
                                        @else
                                            <button class="btn btn-default btn-xs" type="submit"
                                                    title="{{ trans('econf.committee.make_chair') }}">
                                                <span class="fa fa-star"></span>
                                            </button>

                                        @endif
                                        <a href="mailto:{{ $user->email }}"
                                           class="btn btn-default" title="{{ trans('econf.actions.send_email') }}">
                                            <span class="fa fa-envelope"></span>
                                        </a>
                                        <a href="#" class="btn btn-danger"
                                           title="{{ trans('econf.committee.remove_user') }}"
                                           data-toggle="modal" data-target="#deleteModal{{ $user->id }}">
                                            <span class="fa fa-trash"></span>
                                        </a>
                                    </div>
                                    {!! BootForm::close() !!}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>

            <div class="box-footer">
            <span class="text-muted">
                {{ trans('econf.layout.results', ['from' => $users->firstItem(), 'to' => $users->lastItem(), 'total' => $users->total()]) }}
            </span>
                <div class="box-tools pull-right">
                    {!! $users->links() !!}
                </div>
            </div>
        </div>


    </section>

    <!-- Add user modal -->

    <div class="modal fade" id="addUserModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title">
                        {{ trans('econf.committee.invite_user') }}
                    </h4>
                </div>
                {!! BootForm::open()->action(m_action('\\'.$class.'@addUser'))->put() !!}
                <div class="modal-body">
                    {!! BootForm::textarea(trans('econf.user.email'), 'email')->rows(2)->helpBlock(trans('econf.committee.one_per_line')) !!}
                    {!! BootForm::checkbox(trans('econf.committee.chair'), 'chair') !!}
                    {!! BootForm::textarea(trans('econf.admin.email.message'), 'message')->addClass('koala-simple') !!}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    {!! BootForm::submit(trans('econf.actions.invite'), 'btn-primary') !!}
                </div>
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>

    @foreach($users as $user)
        @if($user->id != Auth::id())
            <div class="modal modal-danger fade" id="deleteModal{{ $user->id }}">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <h4 class="modal-title">
                                {{ trans('econf.committee.remove_user') }}
                            </h4>
                        </div>
                        <div class="modal-body">
                            <p>{!! trans('econf.committee.remove_confirmation', ['name' => $user->name, 'committee' => $committee->full_name()]) !!}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">
                                {{ trans('econf.actions.cancel') }}
                            </button>
                            {!! BootForm::open()->action(m_action('\\'.$class.'@removeUser', $user))->delete() !!}
                            {!! BootForm::submit(trans('econf.actions.remove'), 'btn-outline') !!}
                            {!! BootForm::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    @endforeach

@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            {{ trans('econf.dashboard.dashboard') }}
        </h1>
        {!! Breadcrumbs::render('admin.dashboard') !!}
    </section>

    <!-- Main content -->
    <section class="content">

        @include('flash::message')

        @in('organizing')

        <div class="row">

            @foreach($data as $item)

                <div class="col-lg-3 col-sm-6">

                    <div class="info-box {{ !empty($item['class'])?$item['class']:'bg-aqua' }}">
                        <span class="info-box-icon"><i class="{{ $item['icon'] }}"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">{{ $item['label'] }}</span>
                            <span class="info-box-number">
                                {{ $item['value'] }}
                                @if(!empty($item['small']))
                                    <small>{{ $item['small'] }}</small>
                                @endif
                            </span>

                            @if(!empty($item['progress']) || !empty($item['footer']))
                                <div class="progress">
                                    <div class="progress-bar"
                                         style="width: {{ !empty($item['progress'])?$item['progress']:0 }}%"></div>
                                </div>
                                <span class="progress-description">
                                {{ !empty($item['footer'])?$item['footer']:(Setting::get('conf-short_name', Setting::get('conf-name'))) }}
                              </span>
                            @endif
                        </div>
                        <!-- /.info-box-content -->
                    </div>

                </div>

            @endforeach

        </div>

        @endin

        @action('dashboard.html')

        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="box box-default">
                    <div class="box-header">
                        <h3 class="box-title">
                            {{ trans('econf.admin.important_dates') }}
                        </h3>
                    </div>
                    <div class="box-body">
                        <ul class="list-group list-group-unbordered">
                            @foreach($calendar as $dates)
                                <li class="list-group-item">
                                    <strong>{{ $dates['label'] }}</strong><br/>
                                    {{ $dates['start']->format(trans('econf.date.longDate')) }}
                                    {{ trans('econf.public.to') }}
                                    {{ $dates['end']->format(trans('econf.date.longDate')) }}
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection

resources/views/admin/session_types.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            {{ trans('econf.session_types.label') }}
        </h1>
        {!! Breadcrumbs::render('admin.settings.session_types') !!}
    </section>

    <!-- Main content -->
    <section class="content">

        @include('flash::message')

        <p>
            <a class="btn btn-default" title="{{ trans('econf.actions.create') }}"
               data-toggle="modal" data-target="#createType">
                <span class="fa fa-plus"></span> {{ trans('econf.actions.create') }}
            </a>
        </p>


        <div class="box box-default">
            <div class="box-body no-padding">
                <table class="table">
                    <thead>
                    <tr>
                        <th>{{ trans('econf.session_types.name') }}</th>
                        <th>{{ trans('econf.session_types.duration_min') }}</th>
                        <th>{{ trans('econf.session_types.parallel') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(\App\SessionType::all() as $session_type)
                        <tr>
                            <td>{{ $session_type->name }}</td>
                            <td>{{ $session_type->duration }}</td>
                            <td>
                                @if($session_type->parallel)
                                    <span class="fa fa-check text-success"></span>
                                @else
                                    <span class="fa fa-times text-muted"></span>
                                @endif
                            </td>
                            <td class="text-right">
                                <div class="btn-group btn-group-xs">
                                    <a class="btn btn-default" title="{{ trans('econf.actions.edit') }}"
                                       data-toggle="modal" data-target="#edit{{ $session_type->id }}">
                                        <span class="fa fa-pencil"></span>
                                    </a>
                                    <a class="btn btn-danger" title="{{ trans('econf.actions.delete') }}"
                                       data-toggle="modal" data-target="#delete{{ $session_type->id }}">
                                        <span class="fa fa-trash"></span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </section>
    <!-- /.content -->

    <div class="modal modal-default" id="createType">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">{{ trans('econf.session_types.create') }}</h4>
                </div>
                {!! BootForm::open()->action(m_action('Admin\SessionTypeController@store')) !!}
                <div class="modal-body">
                    {!! BootForm::text(trans('econf.session_types.name'), 'name') !!}
                    {!! BootForm::text(trans('econf.session_types.duration_min'), 'duration')->attribute('type', 'number')->attribute('min', 0)->attribute('step', 1) !!}
                    {!! BootForm::checkbox(trans('econf.session_types.parallel'), 'parallel') !!}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
                        {{ trans('econf.actions.cancel') }}
                    </button>
                    {!! BootForm::submit(trans('econf.actions.create'), 'btn-primary') !!}
                </div>
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>

    @foreach(\App\SessionType::all() as $session_type)

        <div class="modal modal-default" id="edit{{ $session_type->id }}">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                        <h4 class="modal-title">{{ trans('econf.session_types.edit') }}</h4>
                    </div>
                    {!! BootForm::open()->action(m_action('Admin\SessionTypeController@update', $session_type))->put() !!}
                    {!! BootForm::bind($session_type) !!}
                    <div class="modal-body">
                        {!! BootForm::text(trans('econf.session_types.name'), 'name') !!}
                        {!! BootForm::text(trans('econf.session_types.duration_min'), 'duration')->attribute('type', 'number')->attribute('min', 0)->attribute('step', 1) !!}
                        {!! BootForm::checkbox(trans('econf.session_types.parallel'), 'parallel') !!}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
                            {{ trans('econf.actions.cancel') }}
                        </button>
                        {!! BootForm::submit(trans('econf.actions.update'), 'btn-primary') !!}
                    </div>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>

        <div class="modal modal-danger" id="delete{{ $session_type->id }}">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                        <h4 class="modal-title">{{ trans('econf.session_types.delete') }}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{!! trans('econf.session_types.delete_confirmation', ['name' => $session_type->name]) !!}</p>
                        <p>{!! trans('econf.layout.delete_warning') !!}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">
                            {{ trans('econf.actions.cancel') }}
                        </button>
                        {!! BootForm::open()->action(m_action('Admin\SessionTypeController@destroy',$session_type))->delete() !!}
                        {!! BootForm::submit(trans('econf.actions.delete'), 'btn-outline') !!}
                        {!! BootForm::close() !!}
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    @endforeach
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            {{ trans('econf.admin.settings.conference.label') }}
        </h1>
        {!! Breadcrumbs::render('admin.settings.conference') !!}
    </section>

    <!-- Main content -->
    <section class="content">

        @include('flash::message')

        {!! BootForm::open()->action(m_action('Admin\SettingsController@store'))->post()->multipart() !!}

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">
                    {{ trans('econf.admin.settings.conference.data') }}
                </h3>
            </div>
            <div class="box-body">

                {!! setting_input(trans('econf.admin.settings.conference.name'), 'conf-name') !!}
                {!! setting_input(trans('econf.admin.settings.conference.short_name'), 'conf-short_name') !!}
                {!! setting_input(trans('econf.admin.settings.conference.email'), 'conf-email', 'email') !!}
                {!! setting_input(trans('econf.admin.settings.conference.start_date'), 'conf-start_date', 'date') !!}
                {!! setting_input(trans('econf.admin.settings.conference.end_date'), 'conf-end_date', 'date') !!}

                {!! BootForm::textarea(trans('econf.admin.settings.conference.topics'), 'topics')->value(old('topics', $topics))->rows(2)->helpBlock(trans('econf.admin.settings.conference.topics_one-per-line')) !!}

            </div>
        </div>

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">
                    {{ trans('econf.admin.settings.conference.brand') }}
                </h3>
            </div>
            <div class="box-body">

                @if(Setting::has('conf-logo'))
                    <div class="settings-logo pull-right img-thumbnail" style="margin-left:10px;">
                        <img src="{{ action('FileController@get', Setting::get('conf-logo')) }}">
                    </div>
                @endif
                {!! BootForm::file(trans('econf.admin.settings.conference.logo'), 'logo')->helpBlock(trans('econf.layout.file_formats', ['types' => 'PNG']))->attribute('accept', 'image/png') !!}

                @if(Setting::has('conf-logo_white'))
                    <div class="settings-logo white pull-right img-thumbnail" style="margin-left:10px;">
                        <img src="{{ action('FileController@get', Setting::get('conf-logo_white')) }}">
                    </div>
                @endif
                {!! BootForm::file(trans('econf.admin.settings.conference.logo_white'), 'logo_white')->helpBlock(trans('econf.layout.file_formats', ['types' => 'PNG']))->attribute('accept', 'image/png') !!}

                @if(Setting::has('conf-icon'))
                    <div class="settings-icon pull-right img-thumbnail" style="margin-left:10px;">
                        <img src="{{ action('FileController@get', Setting::get('conf-icon')) }}" class="img-rounded">
                    </div>
                @endif
                {!! BootForm::file(trans('econf.admin.settings.conference.icon'), 'icon')->helpBlock(trans('econf.admin.settings.conference.icon_help').' '.trans('econf.layout.file_formats', ['types' => 'PNG']))->attribute('accept', 'image/png') !!}

                <div class="form-group {!! $errors->has('setting[conf-color]') ? 'has-error' : '' !!}">
                    <label for="setting[school.color]">{{trans('econf.admin.settings.conference.color')}}</label>
                    <div class="input-group colorinput">
                        <span class="input-group-addon"><i></i></span>
                        <input type="text" class="form-control" name="setting[conf-color]" id="setting[conf-color]"
                               value="{{Setting::get('conf-color', '')}}">
                    </div>
                    {!! $errors->first('setting[conf-color]', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
        </div>

        {!! BootForm::submit(trans('econf.actions.update'), 'btn-primary') !!}

        {!! BootForm::close() !!}

    </section>
    <!-- /.content -->
@endsection